trigger:
- master

variables:
  miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

strategy:
  matrix:
    py37:
      python.version: "3.7"
    py36:
      python.version: "3.6"

pool:
  vmImage: ubuntu-16.04

steps:
# Add conda to PATH.
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- script: |
    conda env create -f environment-dev.yml
    conda install -y python=$(python.version)
    source activate pyjanitor-dev
    python setup.py develop
  displayName: 'Install package and dependencies'

- script: |
    pytest
  displayName: 'Run tests'
