steps:
  - script: |
      conda env create -f environment-dev.yml
      conda install -y python=$(python.version)
      $(activate.command) pyjanitor-dev
      python setup.py develop
    displayName: 'Install package and dependencies'
